alert("When I opened Sololearn app");
$(function(){
    $(".course").click(function(){
    $(".selected").css("left","0px");
     $(".selected").css("width","85px");
     $(".heading").html("Learn");
     $("img.course").css("filter","invert(0%)");
     $("img.play").css("filter","invert(30%)");
     $("img.home").css("filter","invert(30%)");
     $("img.code").css("filter","invert(30%)");
     $("img.posts").css("filter","invert(30%)");
     $(".me").hide();
     $(".learn").show();
     $(".javascript").hide();
     $(".af").hide();
     $(".challenge").hide();
    });
    $(".play").click(function(){
    $(".selected").css("left","70px");
     $(".selected").css("width","85px");
     $(".heading").html("Challenge");
     $("img.course").css("filter","invert(30%)");
     $("img.play").css("filter","invert(0%)");
     $("img.home").css("filter","invert(30%)");
     $("img.code").css("filter","invert(30%)");
     $("img.posts").css("filter","invert(30%)");
    $(".me").hide();
     $(".javascript").hide();
       $(".learn").hide();
     $(".af").hide();
     $(".challenge").show();
    });
    $(".home").click(function(){
    $(".selected").css("left","140px");
     $(".selected").css("width","85px");
     $(".heading").html("Activity Feed");
     $("img.course").css("filter","invert(30%)");
     $("img.play").css("filter","invert(30%)");
     $("img.home").css("filter","invert(0%)");
     $("img.code").css("filter","invert(30%)");
     $("img.posts").css("filter","invert(30%)");
    $(".me").show();
     $(".javascript").show();
     $(".af").show();
       $(".learn").hide();
     $(".challenge").hide();
    });
    $(".code").click(function(){
    $(".selected").css("left","220px");
     $(".selected").css("width","85px");
     $(".heading").html("Code Playground");
     $("img.course").css("filter","invert(30%)");
     $("img.play").css("filter","invert(30%)");
     $("img.home").css("filter","invert(30%)");
     $("img.code").css("filter","invert(0%)");
     $("img.posts").css("filter","invert(30%)");
    $(".me").hide();
     $(".javascript").hide();
     $(".af").hide();
       $(".learn").hide();
     $(".challenge").hide();
    });
    $(".posts").click(function(){
    $(".selected").css("left","280px");
     $(".selected").css("width","75px");
     $(".heading").html("Q&A Discussions");
     $("img.course").css("filter","invert(30%)");
     $("img.play").css("filter","invert(30%)");
     $("img.home").css("filter","invert(30%)");
     $("img.code").css("filter","invert(30%)");
     $("img.posts").css("filter","invert(0%)");
    $(".me").hide();
     $(".javascript").hide();
     $(".af").hide();
       $(".learn").hide();
     $(".challenge").hide();
    });
    $(".javascript").click(function(){
        window.open("https://medium.com/sololearn/why-javascript-is-sexy-9813737d3347");
    });
    $(".challenge").click(function(){
        window.open("https://code.sololearn.com/WUGPpkY9Jhg1/?ref=app")
    });
       $(".learn").click(function(){
        window.open("http://www.sololearn.com/Course/")
    });
    $(".me").click(function(){
        window.open("https://www.sololearn.com/Profile/3268934")
    });
})